[package]
name = "day14"
version.workspace = true
edition.workspace = true

[dependencies]
eyre.workspace = true
utils = { workspace = true, optional = true }

[features]
default = ["utils"]
utils = ["dep:utils"]
