[package]
name = "utils-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
eyre.workspace = true
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full"] }
