[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
eyre.workspace = true
reqwest = { version = "0.11.22", features = ["blocking"] }
utils-derive = { path = "../utils-derive" }
